# Generated by Django 5.2.17 on 2026-09-07 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_url', models.URLField(max_length=500)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('discovering', 'Discovering pages'), ('scraping', 'Scraping pages'), ('processing', 'Processing content'), ('saving', 'Saving data'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='starting', max_length=24)),
                ('progress_detail', models.CharField(blank=True, default='', max_length=255)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=800)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_url', models.URLField(max_length=800)),
                ('parent_url', models.URLField(blank=True, default='', max_length=800)),
                ('file_type', models.CharField(default='html', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='scraper.websitesource')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('website', 'url')},
            },
        ),
    ]
