# Generated by Django 5.2.17 on 2026-09-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesource",
            name="document_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="websitesource",
            name="failed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="websitesource",
            name="image_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scrapedpage",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=800),
        ),
        migrations.AddField(
            model_name="scrapedpage",
            name="page_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
