plugins {
    id "com.android.application"
}

android {
    namespace "pk.edu.bahria.policy"
    compileSdk 34

    defaultConfig {
        applicationId "pk.edu.bahria.policy"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
}
