# Generated by Django 5.2.17 on 2026-08-23 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('academic', 'Academic Policies'), ('examination', 'Examination Policies'), ('student_affairs', 'Student Affairs'), ('hr', 'HR Policies'), ('finance', 'Finance Policies'), ('admissions', 'Admissions Policies'), ('leave', 'Leave Policies'), ('attendance', 'Attendance Policies'), ('general', 'General University Policies')], db_index=True, default='general', max_length=32)),
                ('department', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='policies/%Y/%m/')),
                ('file_type', models.CharField(max_length=16)),
                ('version', models.CharField(blank=True, default='1.0', max_length=32)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('vector_id', models.CharField(max_length=128, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
